--- 
title: "Class Notes: Intro to Data Science (301033)"
author: "Ryan G"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---

# Prerequisites
These are topic Notes and Practicals for IntrotoDataSci, the material is:

|Week no. | Topic |
|---|---|
| 1| Introduction to Data Science |
|2 | Supervised Learning: Linear Models 1 |
|3 | Supervised Learning: Linear Models 2 |
|4 | Supervised Learning: Classification (Logistic Regression)|
|5 | Resampling Methods (e.g. Cross-Validation, Training Split etc.)|
|6 | Supervised Learning: Tree Based Methods|
|7 | Supervised learning: Classification (Support Vector Machines)|
|8 | unsupervised learning: Principal Component Analysis|
|9 | STUVAC|
|10 | Unsupervised Learning: Clustering|
|11 | Guest Lecture|
| 12| Guest Lecture|
|13 | Revision|
|14 | Final Exam|

In this unit we will cover:

* Supervised learning: 
    + Linear Models
    + Classification (KNN and Discrimination)
    + Classification and Regression Trees
* Unsupervised Learning:
    + DimensionReduction: Principal Component Analysis
    + Clustering: K Means and Hierarchical
* Unstrucutred Data:
    + Text Mining
* Resampling
* Visualisation
